query QuestionBankList($filters: QuestionBankFilterInput) {
  questionBank(filters: $filters) {
    total
    items {
      id
      questionText
      level
      difficulty
      isActive
      isCustom
      isRequired
      companyPriority
      status
      sourceQuestionId
      topic {
        id
        code
        name
        interviewWeight
        isCustom
        skill {
          id
          code
          name
          isCustom
        }
      }
      profession {
        id
        code
        name
      }
      skills {
        id
        code
        name
        isCustom
      }
    }
  }
}
