import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const operationsDir = path.resolve(
  __dirname,
  '../src/shared/api/graphql/operations',
);
const outputFile = path.resolve(
  __dirname,
  '../src/shared/api/graphql/operations.registry.ts',
);

function minifyGraphql(source: string): string {
  return source
    .split('\n')
    .map((line) => line.replace(/#.*$/, '').trim())
    .filter(Boolean)
    .join(' ');
}

function parseOperationName(document: string): string {
  const match =
    /(?:query|mutation|subscription)\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(document);

  if (!match?.[1]) {
    throw new Error('GraphQL operation name not found');
  }

  return match[1];
}

function hashDocument(document: string): string {
  return createHash('sha256').update(document).digest('hex');
}

function toExportKey(operationName: string): string {
  return operationName;
}

const files = readdirSync(operationsDir)
  .filter((file) => file.endsWith('.graphql'))
  .sort();

const entries = files.map((file) => {
  const source = readFileSync(path.join(operationsDir, file), 'utf8');
  const document = minifyGraphql(source);
  const operationName = parseOperationName(document);
  const sha256Hash = hashDocument(document);

  return {
    exportKey: toExportKey(operationName),
    operationName,
    document,
    sha256Hash,
  };
});

const registryBody = entries
  .map(
    ({ exportKey, operationName, document, sha256Hash }) =>
      `  ${exportKey}: {
    operationName: '${operationName}',
    document: ${JSON.stringify(document)},
    sha256Hash: '${sha256Hash}',
  }`,
  )
  .join(',\n');

const output = `// Auto-generated by scripts/graphql-sync.mts — do not edit manually.

export type GraphqlOperationDef = {
  operationName: string;
  document: string;
  sha256Hash: string;
};

export const GraphqlOperations = {
${registryBody}
} as const satisfies Record<string, GraphqlOperationDef>;

export type GraphqlOperationKey = keyof typeof GraphqlOperations;
`;

writeFileSync(outputFile, output);
console.log(`Generated ${outputFile} (${entries.length} operations)`);
