// Auto-generated by scripts/graphql-sync.mts — do not edit manually.

export type GraphqlOperationDef = {
  operationName: string;
  document: string;
  sha256Hash: string;
};

export const GraphqlOperations = {
  AdaptiveCheckpointReviewByAttempt: {
    operationName: 'AdaptiveCheckpointReviewByAttempt',
    document: "query AdaptiveCheckpointReviewByAttempt($attemptId: ID!) { adaptiveCheckpointReviewByAttempt(attemptId: $attemptId) { attemptId needsManualReview redFlags { checkpointKey checkpointTitle summary candidateQuote severity } questionGroups { interviewQuestionId questionText idealAnswer needsManualReview checkpoints { checkpointKey checkpointTitle status scoreAwarded maxScore rationale evidenceSummary confidence needsManualReview depthLabel coveragePercent accuracyPercent } } } }",
    sha256Hash: 'fd13a87f04265b8353665f8bd29400d78d06bc2146b3f88c6830c38a336b899e',
  },
  AddCandidateToShortlist: {
    operationName: 'AddCandidateToShortlist',
    document: "mutation AddCandidateToShortlist($candidateId: ID!, $reason: String) { addCandidateToShortlist(candidateId: $candidateId, reason: $reason) { candidateId status reason } }",
    sha256Hash: '945eb92bf90b01f4c657538dc82aa7ec3fc5fc348deffe76e008f5273a0456f2',
  },
  AiCostAnalytics: {
    operationName: 'AiCostAnalytics',
    document: "query AiCostAnalytics($filters: AiCostFilterInput) { aiCostAnalytics(filters: $filters) { kpi { totalCostUsd costPerInterview costPerCandidate totalRequests } byModel { model promptTokens completionTokens totalCostUsd } topExpensiveInterviews { interviewAttemptId interviewTitle totalCostUsd latencyMs } elevenLabs { kpi { totalCostUsd totalCharacters totalRequests } byOperation { operationType characterCount totalCostUsd } } } }",
    sha256Hash: '974d996d3ab9c10f6b6eeac46c5a6a84114d35df066f715d37375c03b0f1a0de',
  },
  ArchiveInterview: {
    operationName: 'ArchiveInterview',
    document: "mutation ArchiveInterview($id: ID!) { archiveInterview(id: $id) { id status publicUrl } }",
    sha256Hash: '8a07c6cf003bf6fae30396828feac82d425890c88f69d9b2ad296b79b3526fcf',
  },
  BeginInterviewAttempt: {
    operationName: 'BeginInterviewAttempt',
    document: "mutation BeginInterviewAttempt($input: BeginInterviewAttemptInput!) { beginInterviewAttempt(input: $input) { attemptId status isWelcomePending welcomeMessage totalQuestions answeredQuestions currentQuestionText currentQuestionId messages { id role content sequenceOrder messageKind } } }",
    sha256Hash: '5a6ba59ffe973bcfec75dc962fcdddf3aabab9d65093f8125e6ce207ba72e7e9',
  },
  CandidateReport: {
    operationName: 'CandidateReport',
    document: "query CandidateReport($candidateId: ID!) { candidateReport(candidateId: $candidateId) { candidateId fullName email phone linkedinUrl githubUrl shortlistStatus shortlistReason latestFinalEvaluation { id totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation achievedLevel achievedLevelMethod achievedLevelNote targetLevel levelBreakdown { level earned maxScore ratio passed } summary detailedSummary strengths weaknesses risks needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } interviewHistory { attemptId interviewId interviewTitle jobRole status completedAt totalScore } } }",
    sha256Hash: 'a4e17b7b58c7b9ef7b192b839b9738ec2af0ae189b19b85089b0b7ec968f9c4c',
  },
  CheckpointResultsByAttempt: {
    operationName: 'CheckpointResultsByAttempt',
    document: "query CheckpointResultsByAttempt($attemptId: ID!) { checkpointResultsByAttempt(attemptId: $attemptId) { attemptId questionGroups { interviewQuestionId questionText needsManualReview checkpoints { id checkpointKey checkpointTitle status scoreAwarded maxScore evidenceQuote reasoningShort } } } }",
    sha256Hash: '00b197d53add2a43719d52da38185c665ad2f49a7166454146d7cc372a38d7b1',
  },
  CompanyCandidates: {
    operationName: 'CompanyCandidates',
    document: "query CompanyCandidates($filters: CompanyCandidatesFilterInput) { companyCandidates(filters: $filters) { items { candidateId fullName email interviewsCount avgScore lastInterviewDate shortlistStatus } total page pageSize } }",
    sha256Hash: '94458040d97fcc4f4b704a9b5f22dc8645c637d34db726ccd1c8e79beeb659eb',
  },
  CompanyDashboardOverview: {
    operationName: 'CompanyDashboardOverview',
    document: "query CompanyDashboardOverview { companyDashboardOverview { metrics { candidatesTotal completedTotal inProgressTotal shortlistedTotal abandonedTotal needsReviewTotal strongInviteTotal completionRate interviewsTotal activeInterviewsTotal } interviewsTotal interviews { interviewId title jobRole status level interviewLanguage questionCount publicUrl createdAt attemptsTotal attemptsCompleted attemptsInProgress attemptsAbandoned attemptsPending completionRate shortlistedCount strongInviteCount needsManualReviewCount avgScore lastActivityAt } attentionItems { kind attemptId interviewId interviewTitle jobRole candidateId candidateName overallScore hireRecommendation occurredAt } shortlistTotal shortlistPreview { candidateId fullName email interviewsCount avgScore lastInterviewDate } weakTopics { topicName avgScore passRate sampleCount } } }",
    sha256Hash: '83240fc3c3321cc46cc88529a11c887a8d261762c02167e22b499bbbefff4627',
  },
  CompanyInterviewSummaries: {
    operationName: 'CompanyInterviewSummaries',
    document: "query CompanyInterviewSummaries($filters: CompanyInterviewSummariesFilterInput) { companyInterviewSummaries(filters: $filters) { items { interviewId title jobRole status level interviewLanguage questionCount publicUrl createdAt attemptsTotal attemptsCompleted attemptsInProgress attemptsAbandoned attemptsPending completionRate shortlistedCount strongInviteCount needsManualReviewCount avgScore lastActivityAt } total page pageSize facets { total active draft archived withAttempts } } }",
    sha256Hash: 'edcb91f142667887b2ecdc4619ed68a898a546790b3d55b7db4c2f0ec61de238',
  },
  CompanyInterviewTemplates: {
    operationName: 'CompanyInterviewTemplates',
    document: "query CompanyInterviewTemplates($filters: CompanyInterviewTemplatesFilterInput) { companyInterviewTemplates(filters: $filters) { items { id title jobRole level interviewLanguage questionCount jobDescription professionId isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub status createdAt updatedAt questions { questionId sortOrder } } total page pageSize } }",
    sha256Hash: 'fa4f5355eac928b0b8b9b3e067f01b20853d148726dd74d1e762bd5696a8c067',
  },
  CompanyInterviews: {
    operationName: 'CompanyInterviews',
    document: "query CompanyInterviews($filters: CompanyInterviewsFilterInput) { companyInterviews(filters: $filters) { items { attemptId interviewId interviewTitle jobRole candidateName candidateEmail status startedAt completedAt overallScore } total page pageSize } }",
    sha256Hash: 'acd78f7d9f08e5defd9b44b023f12874b001086d70b32ec324cd292d48b48e12',
  },
  CompleteInterviewAttempt: {
    operationName: 'CompleteInterviewAttempt',
    document: "mutation CompleteInterviewAttempt($publicToken: String!, $attemptId: ID!) { completeInterviewAttempt(publicToken: $publicToken, attemptId: $attemptId) { attemptId status totalQuestions answeredQuestions messages { id role content } } }",
    sha256Hash: '1776b590581c7d0575427d84d1aaaa5c135f6bc892972591b5a1e7acfed00b74',
  },
  CreateInterviewFromTemplate: {
    operationName: 'CreateInterviewFromTemplate',
    document: "mutation CreateInterviewFromTemplate($templateId: ID!) { createInterviewFromTemplate(templateId: $templateId) { id title jobRole level status publicToken publicUrl questionCount interviewerName welcomeMessageTemplate } }",
    sha256Hash: 'bb82d675d84001016d8fba5faebe8d68f04efec5313af375a59cd8ab628d22fb',
  },
  CreateInterviewTemplateFromInterview: {
    operationName: 'CreateInterviewTemplateFromInterview',
    document: "mutation CreateInterviewTemplateFromInterview($interviewId: ID!, $title: String) { createInterviewTemplateFromInterview(interviewId: $interviewId, title: $title) { id title jobRole level interviewLanguage questionCount jobDescription professionId isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub status createdAt updatedAt questions { questionId sortOrder } } }",
    sha256Hash: '4f1354da2c393b16cbc5f7a2b65d19abd214b4ca53fc21e22a5242e0f4d50710',
  },
  CreateInterviewTemplate: {
    operationName: 'CreateInterviewTemplate',
    document: "mutation CreateInterviewTemplate($input: CreateInterviewTemplateInput!) { createInterviewTemplate(input: $input) { id title jobRole level interviewLanguage questionCount jobDescription professionId isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub status createdAt updatedAt questions { questionId sortOrder } } }",
    sha256Hash: '2fc5307df4f69a28c42688c9f18df660d4a3e85c3909d9226897340c02fa4fb6',
  },
  CreateInterview: {
    operationName: 'CreateInterview',
    document: "mutation CreateInterview($input: CreateInterviewInput!) { createInterview(input: $input) { id title jobRole level status publicToken publicUrl questionCount interviewerName welcomeMessageTemplate } }",
    sha256Hash: 'b6b1596454218a45eabacfe27ada9cb66ad2df7b15459e9483f14d45da2c29d0',
  },
  DraftInterviewFromJobDescription: {
    operationName: 'DraftInterviewFromJobDescription',
    document: "mutation DraftInterviewFromJobDescription($input: DraftInterviewFromJobDescriptionInput!) { draftInterviewFromJobDescription(input: $input) { title jobRole professionId level skillIds questionIds generatedByAi } }",
    sha256Hash: 'd04405994b13b69f8460ab24c501b11d6b48d6133e7b32d41f809f529abc3142',
  },
  EvaluateInterviewAttempt: {
    operationName: 'EvaluateInterviewAttempt',
    document: "mutation EvaluateInterviewAttempt($attemptId: ID!) { evaluateInterviewAttempt(attemptId: $attemptId) { questionCount finalEvaluation { id totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation summary needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } } }",
    sha256Hash: '2429eaadb867d49c11f6a87f7631462e64f11cf79a942596c4b66bac961eec66',
  },
  FinalEvaluationByAttempt: {
    operationName: 'FinalEvaluationByAttempt',
    document: "query FinalEvaluationByAttempt($attemptId: ID!) { finalEvaluationByAttempt(attemptId: $attemptId) { id interviewAttemptId totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation summary detailedSummary strengths weaknesses risks needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } }",
    sha256Hash: '49d58bccde94872474e29fdc631ea7558b711ffa83fb3890c341f842ef88615b',
  },
  Hello: {
    operationName: 'Hello',
    document: "query Hello { hello }",
    sha256Hash: '3f710a83decac3d21ddeae7bd265d8c5a48749226d23327b5dfd7031f406a987',
  },
  Interview: {
    operationName: 'Interview',
    document: "query Interview($id: ID!) { interview(id: $id) { id title jobRole status publicUrl questionCount } }",
    sha256Hash: '40e85211a8dfb1a2688f1e64a7f9fdf54ad0e8be581214bd46bf56af170e3c5e',
  },
  InterviewDetails: {
    operationName: 'InterviewDetails',
    document: "query InterviewDetails($interviewId: ID!) { interviewDetails(interviewId: $interviewId) { id title jobRole status questionCount publicUrl createdAt evaluationStatus primaryFinalEvaluation { id totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation summary strengths weaknesses risks needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } attempts { attemptId candidateId candidateName candidateEmail status startedAt completedAt overallScore hireRecommendation evaluationStatus } } }",
    sha256Hash: '93243e0e3d26a43f9fd25da1de04870e34cf5624c09be9ce575a1c61ae04e79a',
  },
  InterviewSession: {
    operationName: 'InterviewSession',
    document: "query InterviewSession($publicToken: String!, $attemptId: ID!) { interviewSession(publicToken: $publicToken, attemptId: $attemptId) { attemptId status totalQuestions answeredQuestions currentQuestionText currentQuestionId welcomeMessage isWelcomePending messages { id role content sequenceOrder messageKind interviewQuestionId targetCheckpointKey } } }",
    sha256Hash: 'a2ec889f92d97cd79687f49d3628adb8e0bbedaf8fc5be80cf1993faa15271f7',
  },
  InterviewTranscript: {
    operationName: 'InterviewTranscript',
    document: "query InterviewTranscript($attemptId: ID!) { interviewTranscript(attemptId: $attemptId) { attemptId segments { messageId role content sequenceOrder timestamp questionText interviewQuestionId } } }",
    sha256Hash: 'c8fbaa5a49e16d13e2de04f98a250b2e517a9cdc5458df598494facaa3d94faa',
  },
  Login: {
    operationName: 'Login',
    document: "mutation Login($input: LoginInput!) { login(input: $input) { accessToken tokenType user { id email fullName isActive } company { id name slug isActive } } }",
    sha256Hash: '57d674640bf98cdc800d6ecb4aade7f1e03722557aeba94697070c918d5df06a',
  },
  Logout: {
    operationName: 'Logout',
    document: "mutation Logout { logout { success } }",
    sha256Hash: 'e95849698f87003740d4746be7f1e4f193cc8bd09afd72059b22a2f460f30674',
  },
  ManagedInterview: {
    operationName: 'ManagedInterview',
    document: "query ManagedInterview($id: ID!) { interview(id: $id) { id title jobRole level interviewLanguage questionCount status publicToken publicUrl isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness expiresAt maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub } }",
    sha256Hash: 'cc8a649c35c1f24acc33d057eec238b56859bcfee5138fbb48ef5cbb08fada23',
  },
  MatchingCandidatesForLevel: {
    operationName: 'MatchingCandidatesForLevel',
    document: "query MatchingCandidatesForLevel( $level: QuestionLevel! $professionId: ID! $skillIds: [ID!] ) { matchingCandidatesForLevel( level: $level professionId: $professionId skillIds: $skillIds ) { candidateId fullName email achievedLevel achievedLevelMethod sourceInterviewId sourceInterviewTitle professionId professionName matchedSkills matchedSkillCount completedAt } }",
    sha256Hash: '05a1131a6a90469d2ad04d87aac0f45b0bcfe264d4183844335381bdefa26039',
  },
  Me: {
    operationName: 'Me',
    document: "query Me { me { user { id email fullName isActive } company { id name slug isActive } } }",
    sha256Hash: '5f9c2503b6ca4fe21e1c16798409bceb2edfa861d45775b9cc7ada9c8275661f',
  },
  PauseInterview: {
    operationName: 'PauseInterview',
    document: "mutation PauseInterview($id: ID!) { pauseInterview(id: $id) { id status publicUrl } }",
    sha256Hash: 'cf8d9ea444df49b4db177569bba7297772b876306198e50599fb3a6dd7d0ed30',
  },
  Professions: {
    operationName: 'Professions',
    document: "query Professions { professions { id code name } }",
    sha256Hash: '369d6ae5ecbf7f85509afba84b0be90ffd1a551e3013b5d3a429e620de299ae5',
  },
  PublicInterview: {
    operationName: 'PublicInterview',
    document: "query PublicInterview($publicToken: String!) { publicInterview(publicToken: $publicToken) { title jobRole questionCount interviewLanguage } }",
    sha256Hash: 'feb1012eb7c31cb2c33da06f91cc874abfa6626a62c1409ab3345d3e381b6ba6',
  },
  PublishInterview: {
    operationName: 'PublishInterview',
    document: "mutation PublishInterview($id: ID!) { publishInterview(id: $id) { id status publicUrl publicToken } }",
    sha256Hash: 'e86d2b2b5c4a402e904bb5d8c4e4b64320284fc1873a34ed389c1fed34853277',
  },
  QuestionBankList: {
    operationName: 'QuestionBankList',
    document: "query QuestionBankList($filters: QuestionBankFilterInput) { questionBank(filters: $filters) { total items { id questionText level difficulty maxScore isActive topic { id code name interviewWeight skill { id code name } } profession { id code name } } } }",
    sha256Hash: '777fa04e2b0d6f4cbe0e6d2916328a7e7aefc6b69ddf1d252ed3f3196795a7fd',
  },
  QuestionBank: {
    operationName: 'QuestionBank',
    document: "query QuestionBank($filters: QuestionBankFilterInput) { questionBank(filters: $filters) { total items { id questionText level difficulty maxScore isActive topic { id code name interviewWeight skill { id code name } } profession { id code name } skills { id code name } checkpoints { id checkpointKey title expected score sortOrder } answerExamples { id exampleType exampleText sortOrder } } } }",
    sha256Hash: 'ba2584cc0ffe8d47aad93c27c7bf7dfaae562e1f605a47dc6df171da1a241428',
  },
  Question: {
    operationName: 'Question',
    document: "query Question($id: ID!) { question(id: $id) { id questionText level difficulty maxScore isActive shortAnswer idealAnswer topic { id code name interviewWeight } profession { id code name } checkpoints { id checkpointKey title expected score sortOrder } answerExamples { id exampleType exampleText sortOrder } } }",
    sha256Hash: 'ed4a698a5b73241e881c7749af32ffd214c44872851832241deb67844fca8f2f',
  },
  RefreshTokens: {
    operationName: 'RefreshTokens',
    document: "mutation RefreshTokens { refreshTokens { accessToken tokenType } }",
    sha256Hash: '87660a9aa0dc1e5e96b0b7cf6cf53e0d67672f2a112a1aced2b13ddc65ed7980',
  },
  Register: {
    operationName: 'Register',
    document: "mutation Register($input: RegisterInput!) { register(input: $input) { accessToken tokenType user { id email fullName isActive } company { id name slug isActive } } }",
    sha256Hash: 'eacb35598acea114d9b5e3476c08021f098294de483f7f6b957ab12019a5d762',
  },
  RemoveCandidateFromShortlist: {
    operationName: 'RemoveCandidateFromShortlist',
    document: "mutation RemoveCandidateFromShortlist($candidateId: ID!, $reason: String) { removeCandidateFromShortlist(candidateId: $candidateId, reason: $reason) { candidateId status reason } }",
    sha256Hash: 'eea0840468dc86c5c2b7077fce042f4746bd0187d09973782c889c57d871aa03',
  },
  ResumeInterview: {
    operationName: 'ResumeInterview',
    document: "mutation ResumeInterview($id: ID!) { resumeInterview(id: $id) { id status publicUrl } }",
    sha256Hash: 'f34aa727711a825eec4e41de202d13915c5ac789f9e417f16bcbbbb074b6c79f',
  },
  Skills: {
    operationName: 'Skills',
    document: "query Skills($professionId: String) { skills(professionId: $professionId) { id code name } }",
    sha256Hash: '148ef1051043f9005da10edfbbfc985b02e4ca8dfcd44b96516683e2138c4ff5',
  },
  StartInterviewPreview: {
    operationName: 'StartInterviewPreview',
    document: "mutation StartInterviewPreview($interviewId: ID!) { startInterviewPreview(interviewId: $interviewId) { attemptId publicToken totalQuestions } }",
    sha256Hash: '47035fcb423791da694c0d133421f3345e121c5dc403b62c221d689f5f436ec6',
  },
  StartPublicInterview: {
    operationName: 'StartPublicInterview',
    document: "mutation StartPublicInterview($input: StartPublicInterviewInput!) { startPublicInterview(input: $input) { attemptId currentQuestionText totalQuestions } }",
    sha256Hash: '032a7de3478909ccacd75f2493a53e8cd385ff297a67a9277bea7569b2c799ea',
  },
  SubmitInterviewAnswer: {
    operationName: 'SubmitInterviewAnswer',
    document: "mutation SubmitInterviewAnswer($input: SubmitInterviewAnswerInput!) { submitInterviewAnswer(input: $input) { status nextQuestionText pendingMessageText answeredQuestions totalQuestions answeredMainQuestions totalMainQuestions messageKind currentInterviewQuestionId isFollowUp currentQuestionFollowUpCount } }",
    sha256Hash: 'b936b668f3732ef1f268034d8e43866bbc1946f0fb16661a2262fabe0f2336ee',
  },
  SuggestInterviewQuestions: {
    operationName: 'SuggestInterviewQuestions',
    document: "mutation SuggestInterviewQuestions($input: SuggestInterviewQuestionsInput!) { suggestInterviewQuestions(input: $input) { count candidateCount generatedByAi questionIds } }",
    sha256Hash: '548e97bfb30507f661119cd0bfcb368f2ab97e0d5a0d41b37bcd6aa0fbecb372',
  },
  TopicSkillQuestionAnalytics: {
    operationName: 'TopicSkillQuestionAnalytics',
    document: "query TopicSkillQuestionAnalytics($filters: TopicSkillQuestionFilterInput) { topicSkillQuestionAnalytics(filters: $filters) { totalCompletedAttempts lowSampleWarning topics { topicName avgScore passRate sampleCount } skills { skillName avgScore passRate sampleCount } questions { questionId questionText avgScore passRate sampleCount } } }",
    sha256Hash: 'd8d55accebfe184107870db37acbac5f49a6e2f398eb354ae6d694ed370c2df6',
  },
  Topics: {
    operationName: 'Topics',
    document: "query Topics($skillId: String, $professionId: String) { topics(skillId: $skillId, professionId: $professionId) { id code name interviewWeight skill { id code name } } }",
    sha256Hash: 'a78c2e047042507f75586d4941996475caccad3655195013f2a02043f903bb4c',
  }
} as const satisfies Record<string, GraphqlOperationDef>;

export type GraphqlOperationKey = keyof typeof GraphqlOperations;
