// Auto-generated by scripts/graphql-sync.mts — do not edit manually.

export type GraphqlOperationDef = {
  operationName: string;
  document: string;
  sha256Hash: string;
};

export const GraphqlOperations = {
  AdaptiveCheckpointReviewByAttempt: {
    operationName: 'AdaptiveCheckpointReviewByAttempt',
    document: "query AdaptiveCheckpointReviewByAttempt($attemptId: ID!) { adaptiveCheckpointReviewByAttempt(attemptId: $attemptId) { attemptId needsManualReview redFlags { checkpointKey checkpointTitle summary candidateQuote severity } questionGroups { interviewQuestionId questionText idealAnswer needsManualReview checkpoints { checkpointKey checkpointTitle status scoreAwarded maxScore rationale evidenceSummary confidence needsManualReview depthLabel coveragePercent accuracyPercent } } } }",
    sha256Hash: 'fd13a87f04265b8353665f8bd29400d78d06bc2146b3f88c6830c38a336b899e',
  },
  AddCandidateToShortlist: {
    operationName: 'AddCandidateToShortlist',
    document: "mutation AddCandidateToShortlist($candidateId: ID!, $reason: String) { addCandidateToShortlist(candidateId: $candidateId, reason: $reason) { candidateId status reason } }",
    sha256Hash: '945eb92bf90b01f4c657538dc82aa7ec3fc5fc348deffe76e008f5273a0456f2',
  },
  AiCostAnalytics: {
    operationName: 'AiCostAnalytics',
    document: "query AiCostAnalytics($filters: AiCostFilterInput) { aiCostAnalytics(filters: $filters) { kpi { totalCostUsd costPerInterview costPerCandidate totalRequests } byModel { model promptTokens completionTokens totalCostUsd } topExpensiveInterviews { interviewAttemptId interviewTitle totalCostUsd latencyMs } elevenLabs { kpi { totalCostUsd totalCharacters totalRequests } byOperation { operationType characterCount totalCostUsd } } } }",
    sha256Hash: '974d996d3ab9c10f6b6eeac46c5a6a84114d35df066f715d37375c03b0f1a0de',
  },
  ApplyPlaybookToInterviewDraft: {
    operationName: 'ApplyPlaybookToInterviewDraft',
    document: "mutation ApplyPlaybookToInterviewDraft($playbookId: ID!, $count: Int) { applyPlaybookToInterviewDraft(playbookId: $playbookId, count: $count) { questionIds pinnedQuestionIds count } }",
    sha256Hash: '9c33c14802d78807c7ea473516aa2404dbb5185895666091a6c3b138d83e321a',
  },
  ArchiveCompanyQuestionPlaybook: {
    operationName: 'ArchiveCompanyQuestionPlaybook',
    document: "mutation ArchiveCompanyQuestionPlaybook($id: ID!) { archiveCompanyQuestionPlaybook(id: $id) }",
    sha256Hash: '7d7a54f4c1a0cae95a7949653c60e24e57c64f1fe76e9658eecb0c7ddab6c3fd',
  },
  ArchiveCompanySkill: {
    operationName: 'ArchiveCompanySkill',
    document: "mutation ArchiveCompanySkill($id: ID!) { archiveCompanySkill(id: $id) { id code name isCustom } }",
    sha256Hash: '6b528d916541e1b2b2da09b1ae260ff4b9be8e8595335b57a248e54537f1c174',
  },
  ArchiveCompanyTopic: {
    operationName: 'ArchiveCompanyTopic',
    document: "mutation ArchiveCompanyTopic($id: ID!) { archiveCompanyTopic(id: $id) { id code name interviewWeight isCustom } }",
    sha256Hash: '03e5f3d637efa5ef4d5a60f90989af85ca7235d5696bf755fbb5e632ead9122b',
  },
  ArchiveInterview: {
    operationName: 'ArchiveInterview',
    document: "mutation ArchiveInterview($id: ID!) { archiveInterview(id: $id) { id status publicUrl } }",
    sha256Hash: '8a07c6cf003bf6fae30396828feac82d425890c88f69d9b2ad296b79b3526fcf',
  },
  ArchiveQuestion: {
    operationName: 'ArchiveQuestion',
    document: "mutation ArchiveQuestion($id: ID!) { archiveQuestion(id: $id) { id isActive } }",
    sha256Hash: 'ba26404b2fe33f9896863a1ea8e5cbd646aed6ba2f6a8f662d6e832d66012044',
  },
  AttemptReviewDecisionHistory: {
    operationName: 'AttemptReviewDecisionHistory',
    document: "query AttemptReviewDecisionHistory( $attemptId: ID! $filters: AttemptReviewDecisionHistoryFilterInput ) { attemptReviewDecisionHistory(attemptId: $attemptId, filters: $filters) { items { eventId source action previousValue newValue reason actorEmail actorName occurredAt } total page pageSize } }",
    sha256Hash: '1e7dde7239ee79fc026f75ed5862a69f651f86cad5c11a7f18e0ef31e9169ff2',
  },
  AttemptReviewNotes: {
    operationName: 'AttemptReviewNotes',
    document: "query AttemptReviewNotes($attemptId: ID!) { attemptReviewNotes(attemptId: $attemptId) { id attemptId body authorId authorName createdAt updatedAt } }",
    sha256Hash: '865e4b8d6e97c83c33de3550ae95eecca3c484b8d3eddba1f008d73663ef314c',
  },
  AttemptShareLink: {
    operationName: 'AttemptShareLink',
    document: "query AttemptShareLink($attemptId: ID!) { attemptShareLink(attemptId: $attemptId) { attemptId token sharePath expiresAt } }",
    sha256Hash: 'e990143086f6913134ed3ee889bb0c8a4d25ad7360fa97887c0925296f6edcdb',
  },
  BeginInterviewAttempt: {
    operationName: 'BeginInterviewAttempt',
    document: "mutation BeginInterviewAttempt($input: BeginInterviewAttemptInput!) { beginInterviewAttempt(input: $input) { attemptId status isWelcomePending welcomeMessage totalQuestions answeredQuestions currentQuestionText currentQuestionId messages { id role content sequenceOrder messageKind } } }",
    sha256Hash: '5a6ba59ffe973bcfec75dc962fcdddf3aabab9d65093f8125e6ce207ba72e7e9',
  },
  CandidateReport: {
    operationName: 'CandidateReport',
    document: "query CandidateReport($candidateId: ID!) { candidateReport(candidateId: $candidateId) { candidateId fullName email phone linkedinUrl githubUrl shortlistStatus shortlistReason latestFinalEvaluation { id totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation achievedLevel achievedLevelMethod achievedLevelNote targetLevel levelBreakdown { level earned maxScore ratio passed } summary detailedSummary strengths weaknesses risks needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } interviewHistory { attemptId interviewId interviewTitle jobRole status completedAt totalScore } } }",
    sha256Hash: 'a4e17b7b58c7b9ef7b192b839b9738ec2af0ae189b19b85089b0b7ec968f9c4c',
  },
  CheckpointResultsByAttempt: {
    operationName: 'CheckpointResultsByAttempt',
    document: "query CheckpointResultsByAttempt($attemptId: ID!) { checkpointResultsByAttempt(attemptId: $attemptId) { attemptId questionGroups { interviewQuestionId questionText needsManualReview checkpoints { id checkpointKey checkpointTitle status scoreAwarded maxScore evidenceQuote reasoningShort } } } }",
    sha256Hash: '00b197d53add2a43719d52da38185c665ad2f49a7166454146d7cc372a38d7b1',
  },
  CommitCompanyQuestionImport: {
    operationName: 'CommitCompanyQuestionImport',
    document: "mutation CommitCompanyQuestionImport($input: CommitCompanyQuestionImportInput!) { commitCompanyQuestionImport(input: $input) { topicsCreated topicsUpdated skillsCreated questionsCreated questionsUpdated } }",
    sha256Hash: 'f4fb9793fb309da94b5b604342ce60fef65c0b3fd432207b815c133a8215e1e1',
  },
  CompanyCandidates: {
    operationName: 'CompanyCandidates',
    document: "query CompanyCandidates($filters: CompanyCandidatesFilterInput) { companyCandidates(filters: $filters) { items { candidateId fullName email interviewsCount avgScore lastInterviewDate shortlistStatus } total page pageSize } }",
    sha256Hash: '94458040d97fcc4f4b704a9b5f22dc8645c637d34db726ccd1c8e79beeb659eb',
  },
  CompanyDashboardOverview: {
    operationName: 'CompanyDashboardOverview',
    document: "query CompanyDashboardOverview { companyDashboardOverview { metrics { candidatesTotal completedTotal inProgressTotal shortlistedTotal abandonedTotal needsReviewTotal strongInviteTotal completionRate interviewsTotal activeInterviewsTotal } interviewsTotal interviews { interviewId title jobRole status level interviewLanguage questionCount publicUrl createdAt attemptsTotal attemptsCompleted attemptsInProgress attemptsAbandoned attemptsPending completionRate shortlistedCount strongInviteCount needsManualReviewCount avgScore lastActivityAt } attentionItems { kind attemptId interviewId interviewTitle jobRole candidateId candidateName overallScore hireRecommendation occurredAt } shortlistTotal shortlistPreview { candidateId fullName email interviewsCount avgScore lastInterviewDate } weakTopics { topicName avgScore passRate sampleCount } } }",
    sha256Hash: '83240fc3c3321cc46cc88529a11c887a8d261762c02167e22b499bbbefff4627',
  },
  CompanyInterviewSummaries: {
    operationName: 'CompanyInterviewSummaries',
    document: "query CompanyInterviewSummaries($filters: CompanyInterviewSummariesFilterInput) { companyInterviewSummaries(filters: $filters) { items { interviewId title jobRole status level interviewLanguage questionCount publicUrl createdAt attemptsTotal attemptsCompleted attemptsInProgress attemptsAbandoned attemptsPending completionRate shortlistedCount strongInviteCount needsManualReviewCount avgScore lastActivityAt } total page pageSize facets { total active draft archived withAttempts } } }",
    sha256Hash: 'edcb91f142667887b2ecdc4619ed68a898a546790b3d55b7db4c2f0ec61de238',
  },
  CompanyInterviewTemplates: {
    operationName: 'CompanyInterviewTemplates',
    document: "query CompanyInterviewTemplates($filters: CompanyInterviewTemplatesFilterInput) { companyInterviewTemplates(filters: $filters) { items { id title jobRole level interviewLanguage questionCount jobDescription professionId isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub status createdAt updatedAt questions { questionId sortOrder } } total page pageSize } }",
    sha256Hash: 'fa4f5355eac928b0b8b9b3e067f01b20853d148726dd74d1e762bd5696a8c067',
  },
  CompanyInterviews: {
    operationName: 'CompanyInterviews',
    document: "query CompanyInterviews($filters: CompanyInterviewsFilterInput) { companyInterviews(filters: $filters) { items { attemptId interviewId interviewTitle jobRole candidateName candidateEmail status startedAt completedAt overallScore } total page pageSize } }",
    sha256Hash: 'acd78f7d9f08e5defd9b44b023f12874b001086d70b32ec324cd292d48b48e12',
  },
  CompanyQuestionOverride: {
    operationName: 'CompanyQuestionOverride',
    document: "query CompanyQuestionOverride($sourceQuestionId: ID!) { companyQuestionOverride(sourceQuestionId: $sourceQuestionId) { id sourceQuestionId extraMustConcepts extraFalseClaims topicWeightOverride updatedAt } }",
    sha256Hash: '54471577b9211a7619f36b009327249d38b4a4789f3a2a42f3a92894bca5fdaf',
  },
  CompanyQuestionPlaybooks: {
    operationName: 'CompanyQuestionPlaybooks',
    document: "query CompanyQuestionPlaybooks { companyQuestionPlaybooks { id name professionId level skillIds isActive itemCount pinnedCount items { questionId sortOrder isPinned } } }",
    sha256Hash: 'db10efc8a6115861ab65a13a583972dc698ca555d08bac347e3ac3e5db2c1d73',
  },
  CompanyReviewQueue: {
    operationName: 'CompanyReviewQueue',
    document: "query CompanyReviewQueue($filters: CompanyReviewQueueFilterInput) { companyReviewQueue(filters: $filters) { items { attemptId candidateId candidateName candidateEmail interviewId interviewTitle jobRole completedAt evaluationStatus totalScore hireRecommendation achievedLevel achievedLevelMethod needsManualReview shortlistStatus } total page pageSize } }",
    sha256Hash: '99abf4d3a906e3002c42c40a8c33ba8f8b26544a45520c1774a746a26bc1f84a',
  },
  CompareInterviewCandidates: {
    operationName: 'CompareInterviewCandidates',
    document: "mutation CompareInterviewCandidates($input: CompareInterviewCandidatesInput!) { compareInterviewCandidates(input: $input) { recommendedAttemptId recommendationTitle recommendationSummary decisionRationale ranking { attemptId rank headline tradeOff } useCases { title recommendedAttemptId rationale } candidateNotes { attemptId candidateName bestFor strengths risks followUpQuestions } caveats } }",
    sha256Hash: '160e55570fd65228c15fb19abeec5ef73d3de9680996dc732c3e79700751021d',
  },
  CompleteInterviewAttempt: {
    operationName: 'CompleteInterviewAttempt',
    document: "mutation CompleteInterviewAttempt($publicToken: String!, $attemptId: ID!) { completeInterviewAttempt(publicToken: $publicToken, attemptId: $attemptId) { attemptId status totalQuestions answeredQuestions messages { id role content } } }",
    sha256Hash: '1776b590581c7d0575427d84d1aaaa5c135f6bc892972591b5a1e7acfed00b74',
  },
  CreateAttemptReviewNote: {
    operationName: 'CreateAttemptReviewNote',
    document: "mutation CreateAttemptReviewNote($input: CreateAttemptReviewNoteInput!) { createAttemptReviewNote(input: $input) { id attemptId body authorId authorName createdAt updatedAt } }",
    sha256Hash: 'c724a0ca419f8645e55488d1b8ba2d95faefbb16be877255174fafd197c6df78',
  },
  CreateAttemptShareLink: {
    operationName: 'CreateAttemptShareLink',
    document: "mutation CreateAttemptShareLink($input: CreateAttemptShareLinkInput!) { createAttemptShareLink(input: $input) { attemptId token sharePath expiresAt } }",
    sha256Hash: '48e263dfdedec5da1c5fc51e0708b6e07906c66f1f3ca718c248827165449a9d',
  },
  CreateCompanyQuestionPlaybook: {
    operationName: 'CreateCompanyQuestionPlaybook',
    document: "mutation CreateCompanyQuestionPlaybook($input: CreateCompanyQuestionPlaybookInput!) { createCompanyQuestionPlaybook(input: $input) { id name professionId level skillIds itemCount pinnedCount items { questionId sortOrder isPinned } } }",
    sha256Hash: '0832d9a38fd1da6c9941c99eaf3a10cd61ca3ddca62932ddb29d0ab8d293484f',
  },
  CreateCompanySkill: {
    operationName: 'CreateCompanySkill',
    document: "mutation CreateCompanySkill($input: CreateCompanySkillInput!) { createCompanySkill(input: $input) { id code name isCustom } }",
    sha256Hash: '04a5070ba9abca9cbd368f86b8be117fa21097a7bb533592b009a8133d83f830',
  },
  CreateCompanyTopic: {
    operationName: 'CreateCompanyTopic',
    document: "mutation CreateCompanyTopic($input: CreateCompanyTopicInput!) { createCompanyTopic(input: $input) { id code name interviewWeight isCustom skill { id code name } } }",
    sha256Hash: '5324942d9708dfc2dd4fee03536839a312b5375968a9d015e943448dbaca2be7',
  },
  CreateInterviewFromTemplate: {
    operationName: 'CreateInterviewFromTemplate',
    document: "mutation CreateInterviewFromTemplate($templateId: ID!) { createInterviewFromTemplate(templateId: $templateId) { id title jobRole level status publicToken publicUrl questionCount interviewerName welcomeMessageTemplate } }",
    sha256Hash: 'bb82d675d84001016d8fba5faebe8d68f04efec5313af375a59cd8ab628d22fb',
  },
  CreateInterviewTemplateFromInterview: {
    operationName: 'CreateInterviewTemplateFromInterview',
    document: "mutation CreateInterviewTemplateFromInterview($interviewId: ID!, $title: String) { createInterviewTemplateFromInterview(interviewId: $interviewId, title: $title) { id title jobRole level interviewLanguage questionCount jobDescription professionId isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub status createdAt updatedAt questions { questionId sortOrder } } }",
    sha256Hash: '4f1354da2c393b16cbc5f7a2b65d19abd214b4ca53fc21e22a5242e0f4d50710',
  },
  CreateInterviewTemplate: {
    operationName: 'CreateInterviewTemplate',
    document: "mutation CreateInterviewTemplate($input: CreateInterviewTemplateInput!) { createInterviewTemplate(input: $input) { id title jobRole level interviewLanguage questionCount jobDescription professionId isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub status createdAt updatedAt questions { questionId sortOrder } } }",
    sha256Hash: '2fc5307df4f69a28c42688c9f18df660d4a3e85c3909d9226897340c02fa4fb6',
  },
  CreateInterview: {
    operationName: 'CreateInterview',
    document: "mutation CreateInterview($input: CreateInterviewInput!) { createInterview(input: $input) { id title jobRole level status publicToken publicUrl questionCount interviewerName welcomeMessageTemplate } }",
    sha256Hash: 'b6b1596454218a45eabacfe27ada9cb66ad2df7b15459e9483f14d45da2c29d0',
  },
  CreateQuestion: {
    operationName: 'CreateQuestion',
    document: "mutation CreateQuestion($input: CreateQuestionInput!) { createQuestion(input: $input) { id questionText status isCustom isRequired companyPriority } }",
    sha256Hash: '78cc485746ab6e9c34d2ef696a38fc04933668a18a26337224ca014260ab6e47',
  },
  DraftInterviewFromJobDescription: {
    operationName: 'DraftInterviewFromJobDescription',
    document: "mutation DraftInterviewFromJobDescription($input: DraftInterviewFromJobDescriptionInput!) { draftInterviewFromJobDescription(input: $input) { title jobRole professionId level skillIds questionIds generatedByAi } }",
    sha256Hash: 'd04405994b13b69f8460ab24c501b11d6b48d6133e7b32d41f809f529abc3142',
  },
  EvaluateInterviewAttempt: {
    operationName: 'EvaluateInterviewAttempt',
    document: "mutation EvaluateInterviewAttempt($attemptId: ID!) { evaluateInterviewAttempt(attemptId: $attemptId) { questionCount finalEvaluation { id totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation summary needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } } }",
    sha256Hash: '2429eaadb867d49c11f6a87f7631462e64f11cf79a942596c4b66bac961eec66',
  },
  FinalEvaluationByAttempt: {
    operationName: 'FinalEvaluationByAttempt',
    document: "query FinalEvaluationByAttempt($attemptId: ID!) { finalEvaluationByAttempt(attemptId: $attemptId) { id interviewAttemptId totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation summary detailedSummary strengths weaknesses risks needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } }",
    sha256Hash: '49d58bccde94872474e29fdc631ea7558b711ffa83fb3890c341f842ef88615b',
  },
  ForkQuestion: {
    operationName: 'ForkQuestion',
    document: "mutation ForkQuestion($sourceQuestionId: ID!) { forkQuestion(sourceQuestionId: $sourceQuestionId) { id questionText status isCustom sourceQuestionId } }",
    sha256Hash: 'c74d7b82b6ad240d2cb8cd48652f95ebbc5cd3c0bf1fb71f76300d5155d03fec',
  },
  Hello: {
    operationName: 'Hello',
    document: "query Hello { hello }",
    sha256Hash: '3f710a83decac3d21ddeae7bd265d8c5a48749226d23327b5dfd7031f406a987',
  },
  InterviewAttemptsPage: {
    operationName: 'InterviewAttemptsPage',
    document: "query InterviewAttemptsPage( $interviewId: ID! $filters: InterviewAttemptsFilterInput ) { interviewAttemptsPage(interviewId: $interviewId, filters: $filters) { total page pageSize items { attemptId candidateId candidateName candidateEmail status completedAt overallScore hireRecommendation evaluationStatus achievedLevel achievedLevelMethod needsManualReview shortlistStatus reviewStatus aiAssessmentVerdict companyDecision reviewedAt hasTeamNotes } } }",
    sha256Hash: 'ea3d134abcc4e510722557b9275fe193974f89d8effd6fe71af210def4d060d9',
  },
  Interview: {
    operationName: 'Interview',
    document: "query Interview($id: ID!) { interview(id: $id) { id title jobRole status publicUrl questionCount } }",
    sha256Hash: '40e85211a8dfb1a2688f1e64a7f9fdf54ad0e8be581214bd46bf56af170e3c5e',
  },
  InterviewDetails: {
    operationName: 'InterviewDetails',
    document: "query InterviewDetails($interviewId: ID!) { interviewDetails(interviewId: $interviewId) { id title jobRole professionName level status questionCount publicUrl createdAt evaluationStatus skills questions { id sortOrder questionText level difficulty topicName } primaryFinalEvaluation { id totalScore finalScore totalWeight averageScore strengthCategory category hireRecommendation summary strengths weaknesses risks needsManualReview categoryBreakdown { categoryKey categoryLabel scoreNormalized weight contribution } topicEvaluations { topic score weight weightedScore strengthCategory } } attempts { attemptId candidateId candidateName candidateEmail status startedAt completedAt overallScore hireRecommendation evaluationStatus achievedLevel achievedLevelMethod needsManualReview shortlistStatus reviewStatus aiAssessmentVerdict companyDecision reviewedAt hasTeamNotes } } }",
    sha256Hash: 'b4bc8493d3119fded6edb26aabd09caa6a89122af4ca7fc3f76e2f83cf79fe95',
  },
  InterviewSession: {
    operationName: 'InterviewSession',
    document: "query InterviewSession($publicToken: String!, $attemptId: ID!) { interviewSession(publicToken: $publicToken, attemptId: $attemptId) { attemptId status totalQuestions answeredQuestions currentQuestionText currentQuestionId welcomeMessage isWelcomePending messages { id role content sequenceOrder messageKind interviewQuestionId targetCheckpointKey } } }",
    sha256Hash: 'a2ec889f92d97cd79687f49d3628adb8e0bbedaf8fc5be80cf1993faa15271f7',
  },
  InterviewTranscript: {
    operationName: 'InterviewTranscript',
    document: "query InterviewTranscript($attemptId: ID!) { interviewTranscript(attemptId: $attemptId) { attemptId segments { messageId role content sequenceOrder timestamp questionText interviewQuestionId } } }",
    sha256Hash: 'c8fbaa5a49e16d13e2de04f98a250b2e517a9cdc5458df598494facaa3d94faa',
  },
  Login: {
    operationName: 'Login',
    document: "mutation Login($input: LoginInput!) { login(input: $input) { accessToken tokenType user { id email fullName isActive } company { id name slug isActive } } }",
    sha256Hash: '57d674640bf98cdc800d6ecb4aade7f1e03722557aeba94697070c918d5df06a',
  },
  Logout: {
    operationName: 'Logout',
    document: "mutation Logout { logout { success } }",
    sha256Hash: 'e95849698f87003740d4746be7f1e4f193cc8bd09afd72059b22a2f460f30674',
  },
  ManagedInterview: {
    operationName: 'ManagedInterview',
    document: "query ManagedInterview($id: ID!) { interview(id: $id) { id title jobRole level interviewLanguage questionCount status publicToken publicUrl isVideoEnabled interviewerName welcomeMessageTemplate aiTone probingDepth scoringStrictness expiresAt maxCompletions allowRetake timeLimitMinutes passingScore requirePhone requireLinkedin requireGithub } }",
    sha256Hash: 'cc8a649c35c1f24acc33d057eec238b56859bcfee5138fbb48ef5cbb08fada23',
  },
  MarkAttemptReviewStarted: {
    operationName: 'MarkAttemptReviewStarted',
    document: "mutation MarkAttemptReviewStarted($attemptId: ID!) { markAttemptReviewStarted(attemptId: $attemptId) { attemptId reviewStatus aiAssessmentVerdict companyDecision reviewedAt } }",
    sha256Hash: '7c8e3f289419b7cbd9a8714e224dc425af458bd0827442ed377337e9168bca69',
  },
  MatchingCandidatesForLevel: {
    operationName: 'MatchingCandidatesForLevel',
    document: "query MatchingCandidatesForLevel( $level: QuestionLevel! $professionId: ID! $skillIds: [ID!] ) { matchingCandidatesForLevel( level: $level professionId: $professionId skillIds: $skillIds ) { candidateId fullName email achievedLevel achievedLevelMethod sourceInterviewId sourceInterviewTitle professionId professionName matchedSkills matchedSkillCount completedAt } }",
    sha256Hash: '05a1131a6a90469d2ad04d87aac0f45b0bcfe264d4183844335381bdefa26039',
  },
  Me: {
    operationName: 'Me',
    document: "query Me { me { user { id email fullName isActive } company { id name slug isActive } } }",
    sha256Hash: '5f9c2503b6ca4fe21e1c16798409bceb2edfa861d45775b9cc7ada9c8275661f',
  },
  PauseInterview: {
    operationName: 'PauseInterview',
    document: "mutation PauseInterview($id: ID!) { pauseInterview(id: $id) { id status publicUrl } }",
    sha256Hash: 'cf8d9ea444df49b4db177569bba7297772b876306198e50599fb3a6dd7d0ed30',
  },
  Professions: {
    operationName: 'Professions',
    document: "query Professions { professions { id code name } }",
    sha256Hash: '369d6ae5ecbf7f85509afba84b0be90ffd1a551e3013b5d3a429e620de299ae5',
  },
  PublicInterview: {
    operationName: 'PublicInterview',
    document: "query PublicInterview($publicToken: String!) { publicInterview(publicToken: $publicToken) { title jobRole questionCount interviewLanguage } }",
    sha256Hash: 'feb1012eb7c31cb2c33da06f91cc874abfa6626a62c1409ab3345d3e381b6ba6',
  },
  PublishInterview: {
    operationName: 'PublishInterview',
    document: "mutation PublishInterview($id: ID!) { publishInterview(id: $id) { id status publicUrl publicToken } }",
    sha256Hash: 'e86d2b2b5c4a402e904bb5d8c4e4b64320284fc1873a34ed389c1fed34853277',
  },
  QuestionBankList: {
    operationName: 'QuestionBankList',
    document: "query QuestionBankList($filters: QuestionBankFilterInput) { questionBank(filters: $filters) { total items { id questionText level difficulty isActive isCustom isRequired companyPriority status sourceQuestionId topic { id code name interviewWeight isCustom skill { id code name isCustom } } profession { id code name } skills { id code name isCustom } } } }",
    sha256Hash: 'ab7edcdfca997865b0542fdd51e144127c48bb96f5530d63be8e3fe8255ed990',
  },
  QuestionBank: {
    operationName: 'QuestionBank',
    document: "query QuestionBank($filters: QuestionBankFilterInput) { questionBank(filters: $filters) { total items { id questionText level difficulty isActive isCustom isRequired companyPriority status sourceQuestionId topic { id code name interviewWeight isCustom skill { id code name isCustom } } profession { id code name } skills { id code name isCustom } checkpoints { id checkpointKey title expected score sortOrder evaluationHints { mustConcepts falseClaims } } answerExamples { id exampleType exampleText sortOrder } } } }",
    sha256Hash: '914cb3441f7ea3f691bfdf036501d073e743043a274bb37cf7c866e7409d40b4',
  },
  Question: {
    operationName: 'Question',
    document: "query Question($id: ID!) { question(id: $id) { id questionText level difficulty isActive isCustom isRequired companyPriority status maxScore shortAnswer idealAnswer sourceQuestionId topic { id code name interviewWeight skill { id code name } } profession { id code name } skills { id code name } checkpoints { id checkpointKey title expected score sortOrder evaluationHints { mustConcepts falseClaims } } answerExamples { id exampleType exampleText sortOrder } } }",
    sha256Hash: '450bd855911f506c1ef332cf381b4377434e5625fae3e880eba2c1051caeb023',
  },
  RefreshTokens: {
    operationName: 'RefreshTokens',
    document: "mutation RefreshTokens { refreshTokens { accessToken tokenType } }",
    sha256Hash: '87660a9aa0dc1e5e96b0b7cf6cf53e0d67672f2a112a1aced2b13ddc65ed7980',
  },
  Register: {
    operationName: 'Register',
    document: "mutation Register($input: RegisterInput!) { register(input: $input) { accessToken tokenType user { id email fullName isActive } company { id name slug isActive } } }",
    sha256Hash: 'eacb35598acea114d9b5e3476c08021f098294de483f7f6b957ab12019a5d762',
  },
  RemoveCandidateFromShortlist: {
    operationName: 'RemoveCandidateFromShortlist',
    document: "mutation RemoveCandidateFromShortlist($candidateId: ID!, $reason: String) { removeCandidateFromShortlist(candidateId: $candidateId, reason: $reason) { candidateId status reason } }",
    sha256Hash: 'eea0840468dc86c5c2b7077fce042f4746bd0187d09973782c889c57d871aa03',
  },
  ResumeInterview: {
    operationName: 'ResumeInterview',
    document: "mutation ResumeInterview($id: ID!) { resumeInterview(id: $id) { id status publicUrl } }",
    sha256Hash: 'f34aa727711a825eec4e41de202d13915c5ac789f9e417f16bcbbbb074b6c79f',
  },
  RevokeAttemptShareLink: {
    operationName: 'RevokeAttemptShareLink',
    document: "mutation RevokeAttemptShareLink($attemptId: ID!) { revokeAttemptShareLink(attemptId: $attemptId) }",
    sha256Hash: '50f6703770300f5b1274856cbb3915ce95034ddcf5f18ee7be88cf13f777b994',
  },
  SetAttemptAiVerdict: {
    operationName: 'SetAttemptAiVerdict',
    document: "mutation SetAttemptAiVerdict($input: SetAttemptAiVerdictInput!) { setAttemptAiVerdict(input: $input) { attemptId reviewStatus aiAssessmentVerdict companyDecision reviewedAt } }",
    sha256Hash: 'eee9a4905b2af1c4515d574c113f4366b636cda5bbb6ef49c549a05371320fd0',
  },
  SetAttemptCompanyDecision: {
    operationName: 'SetAttemptCompanyDecision',
    document: "mutation SetAttemptCompanyDecision($input: SetAttemptCompanyDecisionInput!) { setAttemptCompanyDecision(input: $input) { attemptId reviewStatus aiAssessmentVerdict companyDecision reviewedAt } }",
    sha256Hash: '36a2690fc8e20dae2da47ff49a2583f6e2dd37ef69d26b539421c88499b27533',
  },
  Skills: {
    operationName: 'Skills',
    document: "query Skills($professionId: String) { skills(professionId: $professionId) { id code name isCustom } }",
    sha256Hash: '6b4f2a0f22e18e10bad484f3dcaff1cc67bc30568954d5306854966bf49b810e',
  },
  StartInterviewPreview: {
    operationName: 'StartInterviewPreview',
    document: "mutation StartInterviewPreview($interviewId: ID!) { startInterviewPreview(interviewId: $interviewId) { attemptId publicToken totalQuestions } }",
    sha256Hash: '47035fcb423791da694c0d133421f3345e121c5dc403b62c221d689f5f436ec6',
  },
  StartPublicInterview: {
    operationName: 'StartPublicInterview',
    document: "mutation StartPublicInterview($input: StartPublicInterviewInput!) { startPublicInterview(input: $input) { attemptId currentQuestionText totalQuestions } }",
    sha256Hash: '032a7de3478909ccacd75f2493a53e8cd385ff297a67a9277bea7569b2c799ea',
  },
  SubmitInterviewAnswer: {
    operationName: 'SubmitInterviewAnswer',
    document: "mutation SubmitInterviewAnswer($input: SubmitInterviewAnswerInput!) { submitInterviewAnswer(input: $input) { status nextQuestionText pendingMessageText answeredQuestions totalQuestions answeredMainQuestions totalMainQuestions messageKind currentInterviewQuestionId isFollowUp currentQuestionFollowUpCount } }",
    sha256Hash: 'b936b668f3732ef1f268034d8e43866bbc1946f0fb16661a2262fabe0f2336ee',
  },
  SuggestInterviewQuestions: {
    operationName: 'SuggestInterviewQuestions',
    document: "mutation SuggestInterviewQuestions($input: SuggestInterviewQuestionsInput!) { suggestInterviewQuestions(input: $input) { count candidateCount generatedByAi questionIds questions { id isCustom isRequired companyPriority status } } }",
    sha256Hash: '04b9df445b93fe81b23cad6365f72125b451c8509bd4f622c8342fe7fea43407',
  },
  TopicSkillQuestionAnalytics: {
    operationName: 'TopicSkillQuestionAnalytics',
    document: "query TopicSkillQuestionAnalytics($filters: TopicSkillQuestionFilterInput) { topicSkillQuestionAnalytics(filters: $filters) { totalCompletedAttempts lowSampleWarning topics { topicName avgScore passRate sampleCount } skills { skillName avgScore passRate sampleCount } questions { questionId questionText avgScore passRate sampleCount } } }",
    sha256Hash: 'd8d55accebfe184107870db37acbac5f49a6e2f398eb354ae6d694ed370c2df6',
  },
  Topics: {
    operationName: 'Topics',
    document: "query Topics($skillId: String, $professionId: String) { topics(skillId: $skillId, professionId: $professionId) { id code name interviewWeight isCustom skill { id code name isCustom } } }",
    sha256Hash: '2a1715b650ed538885e901232e2d2effa0ee64fe66639825ecae5da0feac4012',
  },
  UpdateAttemptReviewNote: {
    operationName: 'UpdateAttemptReviewNote',
    document: "mutation UpdateAttemptReviewNote($input: UpdateAttemptReviewNoteInput!) { updateAttemptReviewNote(input: $input) { id attemptId body authorId authorName createdAt updatedAt } }",
    sha256Hash: '3538883d1ec053970e31246767c806082c664f6d0a926acbbe4fa2edb730ffed',
  },
  UpdateCompanySkill: {
    operationName: 'UpdateCompanySkill',
    document: "mutation UpdateCompanySkill($input: UpdateCompanySkillInput!) { updateCompanySkill(input: $input) { id code name isCustom } }",
    sha256Hash: '27b179c3d28f729b1d54dede8172ab311e0df18617243f5b01757b647fd519a5',
  },
  UpdateCompanyTopic: {
    operationName: 'UpdateCompanyTopic',
    document: "mutation UpdateCompanyTopic($input: UpdateCompanyTopicInput!) { updateCompanyTopic(input: $input) { id code name interviewWeight isCustom skill { id code name } } }",
    sha256Hash: '84cc3f028847e646af1aca7acb87535c902d1c9e5acab5deb78c574527403f93',
  },
  UpdateQuestion: {
    operationName: 'UpdateQuestion',
    document: "mutation UpdateQuestion($input: UpdateQuestionInput!) { updateQuestion(input: $input) { id questionText status isCustom isRequired companyPriority } }",
    sha256Hash: 'ac696536192f5fc997fa36bf9f6f7edfe4e1e31a8ce4e30304c9a770d76c51fc',
  },
  UpsertCompanyQuestionOverride: {
    operationName: 'UpsertCompanyQuestionOverride',
    document: "mutation UpsertCompanyQuestionOverride( $input: UpsertCompanyQuestionOverrideInput! ) { upsertCompanyQuestionOverride(input: $input) { id sourceQuestionId extraMustConcepts extraFalseClaims topicWeightOverride updatedAt } }",
    sha256Hash: '4715a6c530e40d171dfde767f4f3175e94d00943e6469ce511340201e7c73105',
  }
} as const satisfies Record<string, GraphqlOperationDef>;

export type GraphqlOperationKey = keyof typeof GraphqlOperations;
